In [4]:
import numpy as np
import random

In [5]:
def getvar(i):
    end = ''
    end += chr(i%26+65)
    if i>25:
        i = i//26 -1
        end = getvar(i)+end
    return end

In [6]:
class column:
    def __init__(self,datatype='ordinal',classes=5,proportions = None,distribution='normalvariate'):
        self.datatype = datatype
        self.classes = classes
        self.proportions = proportions
        self.distribution = distribution
    
    def generate_numerical_column(self,cases,a,b):
        if self.distribution == 'uniform':
            return [random.uniform(a,b) for i in range(cases)]
        elif self.distribution == 'betavariate':
            return [random.betavariate(a,b) for i in range(cases)]   
        elif self.distribution == 'gammavariate':
            return [random.gammavariate(a,b) for i in range(cases)]   
        elif self.distribution == 'gauss':
            return [random.gauss(a,b) for i in range(cases)]   
        elif self.distribution == 'normalvariate':
            return [random.normalvariate(a,b) for i in range(cases)]   
        elif self.distribution == 'weibullvariate':
            return [random.weibullvariate(a,b) for i in range(cases)]
        else:
            return print('Invalid Distribution')
    
    def generate_nominal_column(self,cases):
        if self.datatype == 'ordinal':
            names = ['rank'+str(i) for i in range(self.classes)]
        else:
            names = ['var_'+getvar(i) for i in range(self.classes)]
        if not self.proportions:
            column = random.choices(names,k = cases)
        else:
            if len(names)-len(self.proportions)!=0:
                print("Error, proportions need to be defined for every class")
                return False
            column = random.choices(names,k = cases,weights = self.proportions)
        return column

In [16]:
this = column('numerical', classes=300)
this1 = column('numerical', classes=300)
this2 = column('numerical', classes=300)

In [17]:
import pandas as pd

In [24]:
one = this.generate_numerical_column(100, 5, 2)
two = this1.generate_numerical_column(100, 5, 2)
three = this2.generate_numerical_column(100, 5, 2)
pd.DataFrame([one,two,three]).transpose()

           0         1          2
0   4.848109  7.003286   4.108351
1   5.695281  6.355471   8.147612
2   5.059875  4.659101  11.848934
3   6.739945  4.133664   3.296262
4   4.513554  2.409233   5.252540
..       ...       ...        ...
95  7.132807  7.624616   3.557225
96  4.038059  3.059415   7.108671
97  2.988207  6.986928   7.193478
98  1.419561  3.665146   6.873289
99  8.669015  3.743985   6.336583

[100 rows x 3 columns]